BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Doctor] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [specialty] NVARCHAR(1000),
    [email] NVARCHAR(1000),
    [status] NVARCHAR(1000) NOT NULL CONSTRAINT [Doctor_status_df] DEFAULT 'Active',
    [imageUrl] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Doctor_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Doctor_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
